name: CI

on:
  release:
    types: [published]

jobs:
  build:
    name: Build and Publish (version branch only)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org/'
          cache-dependency-path: ./src/yarn.lock

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./src

      - name: Build Project
        run: yarn build
        working-directory: ./src

      - name: Publish NPM Package
        if: github.ref == 'refs/heads/v5'
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ./.npmrc
          PACKAGE_NAME=$(node -p "require('./package.json').name")
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          if npm view $PACKAGE_NAME@$PACKAGE_VERSION > /dev/null 2>&1; then
            echo "$PACKAGE_NAME version $PACKAGE_VERSION already exists."
            exit 0
          fi
          npm whoami || (echo "❌ NPM_TOKEN invalid!" && exit 1)

          if [[ "$PACKAGE_VERSION" == *-* ]]; then
            echo "Publishing $PACKAGE_NAME@$PACKAGE_VERSION with tag 'next'"
            npm publish --tag next --access public
          else
            echo "Publishing $PACKAGE_NAME@$PACKAGE_VERSION with tag 'latest'"
            npm publish --access public
          fi
        working-directory: ./src
